// types

export const LISTAR_ALBUMES = "LISTAR_ALBUMES";
export const AGREGAR_ALBUM = "AGREGAR_ALBUM";
export const ALBUM_ACTUAL = "ALBUM_ACTUAL";
export const ELIMINAR_ALBUM = "ELIMINAR_ALBUM";

export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const CERRAR_SESION = "CERRAR_SESION";

export const LISTAR_FOTOS = "LISTAR_FOTOS";
